### ISSUE TITLE
"ABOUT" menu item is not active when /about/ is opened.

### ISSUE THREAD

**Issue by antoninpa** [zerostaticthemes/hugo-hero-theme#19] opened 2020-02-14 14:31 UTC
The "ABOUT" menu item does not get any 'active' attribute when I'm on the /about/ page. 
Other menu items work fine.

**Comment by chaw1c1501** [comment] 2020-07-23 11:28
Can someone provide a hint for a fix? I'll try to sort it out.

**Comment by robimalco** [comment] 2020-10-12 10:00
The problem is the structure of the project itself.

The subfolder "pages" does not make sense, since both _history_ and _about_ should be treated on the same level of _homepage_  and _services_.

So to solve this issue, remove the subfolder _pages_ .

**Comment by JugglerX** [comment] 2021-12-26 03:12
Remove the `pages` subfolder will solve the issue. So yes that's an option.

But there is nothing wrong with the current structure. It shows a great example of using subfolders to organize your content while having a different URL structure. Your folder structure does not have to match your URL structure 1:1 and in more complex projects this will inevitably come up. See here you can specify the URL structure for content types in the config.`https://github.com/zerostaticthemes/hugo-hero-theme/blob/cf933e0bc61089c036f2a3cddea857cb86b019d4/exampleSite/config.toml#L54`

The better fix for this issue was to update the header to discover the active menu item using some extra logic.

**Closed** 2021-12-26 03:14 UTC
